### ISSUE TITLE
Removal of old binaries breaks hacl-star's Makefile

### ISSUE THREAD

**Issue by kjacobs-moz** [FStarLang/binaries#1]
A recent commit removed a number of outdated archives from `z3-tested/`: https://github.com/FStarLang/binaries/commit/56fae3ac885c1366502cc500828549189dd20a97

Unfortunately this breaks hacl-star's `make prepare` script which will 404 when trying to fetch: https://github.com/project-everest/hacl-star/blob/master/Makefile.prepare#L52

HACL* could update, (e.g. to self-host), but restoring the archives here will fix downstream consumers without any update. Thanks.

**Comment by msprotz** [comment]
I reinstated the binaries as a temporary fix (so as to not break mozilla CI) but is there any way the Makefile on HACL's master branch could be updated to fetch a specific commit-id (e.g. 9a81bc47b1bbe4b2e914ab9356352fc4c90e497b)? That way we wouldn't need to keep multiple versions of z3 in that repository, which is supposed to only ever hold one version of z3 at a time.

CC @beurdouche 

Let me know if you want a branch, a tag, or something else in that repository.

Thanks,

Jonathan

**Comment by kjacobs-moz** [comment]
Thank you. I'm happy to make the necessary CI changes to support the long-term fix. 

Thanks,
Kevin

**Comment by msprotz** [comment]
Perfect. Let me know if I can be of any further help.

Cheers,

Jonathan

**Comment by msprotz** [comment]
I think @beurdouche has fixed the Makefile on HACL*'s master branch... going to revert this commit then. Thanks!

**Comment by msprotz** [comment]
The commit has been removed from the history (to limit the amount of large blobs in the git history). I believe everything should be fine now.

**Comment by kjacobs-moz** [comment]
Confirmed everything works with the new makefile. Thanks Jonathan and Benjamin!
